@baseUrl = http://localhost:8080
@email = test1@test.com
@password = 123123

### =========================
### CREATE TASK
### =========================
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Попить чайку",
  "description": "Разобраться с указателями, chi и sqlc"
}

### =========================
### GET ALL TASKS
### =========================
GET {{baseUrl}}/tasks

### =========================
### GET TASK BY ID
### =========================
# Заменяй id на нужный
GET {{baseUrl}}/tasks/1

### =========================
### UPDATE TASK (PATCH)
### =========================
PATCH {{baseUrl}}/tasks/1
Content-Type: application/json

{
  "completed": true
}

### =========================
### UPDATE TASK (TITLE + DESCRIPTION)
### =========================
PATCH {{baseUrl}}/tasks/13
Content-Type: application/json

{
  "title": "Изучить Go глубже с чайком",
  "description": "Понять PATCH, middleware и архитектуру"
}

### =========================
### DELETE TASK
### =========================
DELETE {{baseUrl}}/tasks/2

### =========================
### NEGATIVE CASES
### =========================

### Invalid ID
GET {{baseUrl}}/tasks/abc

### Empty PATCH
PATCH {{baseUrl}}/tasks/4
Content-Type: application/json

{}

### Invalid JSON
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "oops",
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### Get tasks (private)
GET {{baseUrl}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA4MTgyNjIsImlhdCI6MTc3MDgxNzM2Miwic3ViIjoxfQ.gNGlCz_s-9ZSqVcoygWFgRCtqc5g_C77774rrUjpubU
### Refresh (manual cookie)
POST {{baseUrl}}/auth/refresh
Cookie: refresh_token=yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzA4OTAwNTAsImlhdCI6MTc3MDgwMzY1MCwic3ViIjo0LCJ0eXAiOiJyZWZyZXNoIn0.E6n9OYKpsChrJP2hHOsK2MhekwKaUBBsOqbEtueo2TI

### Logout
POST {{baseUrl}}/auth/logout
