// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, completed)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, completed, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      int64
	Title       string
	Description string
	Completed   bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Completed,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskByUser = `-- name: DeleteTaskByUser :one
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteTaskByUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteTaskByUser(ctx context.Context, arg DeleteTaskByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteTaskByUser, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTaskByIDByUser = `-- name: GetTaskByIDByUser :one
SELECT id, user_id, title, description, completed, created_at, updated_at
FROM tasks
WHERE id = $1 AND user_id = $2
`

type GetTaskByIDByUserParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTaskByIDByUser(ctx context.Context, arg GetTaskByIDByUserParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByIDByUser, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, user_id, title, description, completed, created_at, updated_at
FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByUserParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskByUser = `-- name: UpdateTaskByUser :one
UPDATE tasks
SET
  title = $3,
  description = $4,
  completed = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, completed, created_at, updated_at
`

type UpdateTaskByUserParams struct {
	ID          int64
	UserID      int64
	Title       string
	Description string
	Completed   bool
}

func (q *Queries) UpdateTaskByUser(ctx context.Context, arg UpdateTaskByUserParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskByUser,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Completed,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
